In [20]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import precision_score

In [ ]:
data = pd.read_csv("bank-full-dataset.csv")
data.head(10)

,Unnamed: 0,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,no
1,1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,no
2,2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,no
3,3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,no
4,4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,no
5,5,35,management,married,tertiary,no,231,yes,no,NaN,5,may,139,1,-1,0,NaN,no
6,6,28,management,single,tertiary,no,447,yes,yes,NaN,5,may,217,1,-1,0,NaN,no
7,7,42,entrepreneur,divorced,tertiary,yes,2,yes,no,NaN,5,may,380,1,-1,0,NaN,no
8,8,58,retired,married,primary,no,121,yes,no,NaN,5,may,50,1,-1,0,NaN,no
9,9,43,technician,single,secondary,no,593,yes,no,NaN,5,may,55,1,-1,0,NaN,no

In [22]:
data.isnull().sum()

Unnamed: 0        0
age               0
job             288
marital           0
education      1857
default           0
balance           0
housing           0
loan              0
contact       13020
day               0
month             0
duration          0
campaign          0
pdays             0
previous          0
poutcome      36959
y                 0
dtype: int64

In [23]:
data = data.drop(["contact", "poutcome"], axis=1)

In [24]:
enc = LabelEncoder()
features_to_convert=["job","marital","default",\
                     "housing","loan","month","y"]
for i in features_to_convert:
    data[i] = enc.fit_transform(data[i].astype('str'))

In [25]:
data['education'] = data['education'].fillna('unknown')
encoder = ['unknown','primary','secondary','tertiary']

for i, word in enumerate(encoder):
    data['education'] = data['education'].astype('str').\
                        str.replace(word, str(i))
data['education'] = data['education'].astype('int64')
data.head()

,Unnamed: 0,age,job,marital,education,default,balance,housing,loan,day,month,duration,campaign,pdays,previous,y
0,0,58,4,1,3,0,2143,1,0,5,8,261,1,-1,0,0
1,1,44,9,2,2,0,29,1,0,5,8,151,1,-1,0,0
2,2,33,2,1,2,0,2,1,1,5,8,76,1,-1,0,0
3,3,47,1,1,0,0,1506,1,0,5,8,92,1,-1,0,0
4,4,33,11,2,0,0,1,0,0,5,8,198,1,-1,0,0

In [26]:
outliers = {}

for i in range(data.shape[1]):
    min_t = data[data.columns[i]].mean() \
            - (3 * data[data.columns[i]].std())
    max_t = data[data.columns[i]].mean() \
            + (3 * data[data.columns[i]].std())
    count = 0

    for j in data[data.columns[i]]:
        if j < min_t or j > max_t:
            count += 1
    outliers[data.columns[i]] = [count, data.shape[0]]

print(outliers)

{'Unnamed: 0': [0, 45211], 'age': [381, 45211], 'job': [0, 45211], 'marital': [0, 45211], 'education': [0, 45211], 'default': [815, 45211], 'balance': [745, 45211], 'housing': [0, 45211], 'loan': [0, 45211], 'day': [0, 45211], 'month': [0, 45211], 'duration': [963, 45211], 'campaign': [840, 45211], 'pdays': [1723, 45211], 'previous': [582, 45211], 'y': [0, 45211]}

In [27]:
X = data.drop("y", axis = 1)
Y = data["y"]

In [28]:
X_new, X_test, \
Y_new, Y_test = train_test_split(X, Y, test_size=0.2,\
                                 random_state = 0)
test_size = X_test.shape[0] / X_new.shape[0]
X_train, X_dev, \
Y_train, Y_dev = train_test_split(X_new, Y_new, \
                                  test_size=test_size,\
                                  random_state = 0)
print(X_train.shape, Y_train.shape, X_dev.shape, \
    Y_dev.shape, X_test.shape, Y_test.shape)

(27125, 15) (27125,) (9043, 15) (9043,) (9043, 15) (9043,)

First Attempt

In [29]:
model_tree = DecisionTreeClassifier(random_state = 2)
model_tree.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=2)

In [30]:
model_NN = MLPClassifier(random_state = 2)
model_NN.fit(X_train, Y_train)

MLPClassifier(random_state=2)

In [31]:
X_sets = [X_train, X_dev, X_test]
Y_sets = [Y_train, Y_dev, Y_test]

precision = []

for i in range(0, len(X_sets)):
    pred = model_tree.predict(X_sets[i])
    score = precision_score(Y_sets[i], pred)
    precision.append(score)

print(precision)

[1.0, 0.5208140610545791, 0.4897959183673469]

In [32]:
X_sets = [X_train, X_dev, X_test]
Y_sets = [Y_train, Y_dev, Y_test]

precision = []

for i in range(0, len(X_sets)):
    pred = model_NN.predict(X_sets[i])
    score = precision_score(Y_sets[i], pred)
    precision.append(score)

print(precision)

[0.4993560849967804, 0.5232342007434945, 0.4641509433962264]

Second Attempt

In [33]:
model_tree = DecisionTreeClassifier(random_state = 2, \
                                    min_samples_leaf=100, \
                                    max_depth=100)
model_tree.fit(X_train, Y_train)

DecisionTreeClassifier(max_depth=100, min_samples_leaf=100, random_state=2)

In [34]:
model_NN = \
    MLPClassifier(random_state = 2, max_iter=1000,\
                  hidden_layer_sizes = [100,100,50,25,25], \
                  tol=1e-4)
model_NN.fit(X_train, Y_train)

MLPClassifier(hidden_layer_sizes=[100, 100, 50, 25, 25], max_iter=1000,
              random_state=2)

In [35]:
X_sets = [X_train, X_dev, X_test]
Y_sets = [Y_train, Y_dev, Y_test]

precision = []

for i in range(0, len(X_sets)):
    pred = model_tree.predict(X_sets[i])
    score = precision_score(Y_sets[i], pred)
    precision.append(score)

print(precision)

[0.6504424778761062, 0.6569264069264069, 0.6016949152542372]

In [36]:
X_sets = [X_train, X_dev, X_test]
Y_sets = [Y_train, Y_dev, Y_test]

precision = []

for i in range(0, len(X_sets)):
    pred = model_NN.predict(X_sets[i])
    score = precision_score(Y_sets[i], pred)
    precision.append(score)

print(precision)

[0.6548821548821548, 0.6435185185185185, 0.6111111111111112]